addons:
  postgresql: "9.4"
language: crystal
before_script:
  - psql -c 'create database crystal;' -U postgres
env:
  - TRAVIS_POSTGRESQL_VERSION=9.4
  - TRAVIS_POSTGRESQL_VERSION=9.3
  - TRAVIS_POSTGRESQL_VERSION=9.2
  - TRAVIS_POSTGRESQL_VERSION=9.1
script:
  - crystal spec | tee /dev/tty | grep "0 failures, 0 errors" -q
notifications:
  email: false
sudo: true
